// Generated by scripts/fetch-kangla-buildings.py — do not edit by hand.
export const KANGLA_BUILDING_COUNTS = {
  total: 49,
  /** Buildings whose height comes from an OSM height or building:levels tag. */
  mapped: 14,
  /** Buildings with no height in OSM, drawn flat at the default below. */
  assumed: 35,
  defaultHeight: 6.0,
} as const;
