/**
 * Recorded narration for the Kangla landmarks, in English, Hindi and Meiteilon.
 *
 * The tracks are static MP3s under `public/audio/kangla/<lang>/`, generated by
 * `npm run audio:kangla` (OpenAI TTS) or `npm run audio:kangla:indic`
 * (ai4bharat/indic-parler-tts, offline). Regenerating is reproducible: the
 * source text below is the same text those scripts read.
 *
 * Why this lives in its own module: two different surfaces show the same three
 * landmarks under two different sets of ids — the Google 3D explorer
 * (`kanglaPlaces`) and the reconstruction experience (`kanglaStops`). Keeping
 * the tracks here, with an alias table, means the audio is written once and
 * neither surface owns it.
 */

export type NarrationLanguage = "en" | "hi" | "mni";

export interface NarrationTrack {
  /** The narration, in that language — also shown on screen. */
  text: string;
  /** Path under `public/`. */
  audio: string;
}

export type NarrationSet = Record<NarrationLanguage, NarrationTrack>;

/**
 * `lang` is the BCP-47 tag, so assistive tech switches voice and the browser
 * picks the right font. `className` pulls in the matching webfont for scripts
 * the body face does not cover.
 */
export const narrationLanguages: {
  code: NarrationLanguage;
  label: string;
  lang: string;
  className?: string;
}[] = [
  { code: "en", label: "English", lang: "en-IN" },
  { code: "hi", label: "हिन्दी", lang: "hi-IN", className: "font-devanagari" },
  { code: "mni", label: "ꯃꯩꯇꯩꯂꯣꯟ", lang: "mni-Mtei", className: "font-mayek" },
];

/** Keyed by narration id — the reconstruction's stop ids. */
export const kanglaNarration: Record<string, NarrationSet> = {
  guardians: {
    en: {
      text: "The paired white guardians stand before the Uttra at Kangla. Their upright bodies, open jaws and long tails make them one of Manipur's most recognisable cultural symbols.",
      audio: "/audio/kangla/en/guardians.mp3",
    },
    hi: {
      text: "कांगला में उत्रा के सामने सफेद कांगला शा की जोड़ी खड़ी है। इनके सीधे खड़े शरीर, खुले जबड़े और लंबी पूंछ इन्हें मणिपुर के सबसे पहचाने जाने वाले सांस्कृतिक प्रतीकों में शामिल करते हैं।",
      audio: "/audio/kangla/hi/guardians.mp3",
    },
    mni: {
      text: "ꯀꯥꯡꯂꯥꯗ ꯎꯠꯇ꯭ꯔꯥꯒꯤ ꯃꯥꯃꯪꯗ ꯀꯥꯡꯂꯥ ꯁꯥ ꯑꯅꯤ ꯂꯩ꯫ ꯃꯈꯣꯏꯒꯤ ꯆꯤꯡ ꯂꯦꯝꯕ ꯍꯛꯆꯥꯡ, ꯂꯥꯎꯅ ꯍꯥꯡꯗꯣꯛꯂꯕ ꯌꯥ ꯑꯃꯁꯨꯡ ꯁꯥꯡꯂꯕ ꯃꯥꯃꯩ ꯃꯅꯤꯄꯨꯔꯒꯤ ꯁꯥꯈꯪꯂꯕ ꯀꯜꯆꯔꯒꯤ ꯈꯨꯗꯥꯝ ꯑꯃꯅꯤ।",
      audio: "/audio/kangla/mni/guardians.mp3",
    },
  },
  "western-gate": {
    en: {
      text: "The western gateway brings together a tall open arch, blue timber-like facades and pale columns. Notice the roof's crossed finials, a distinctive feature in the architectural vocabulary of Kangla.",
      audio: "/audio/kangla/en/western-gate.mp3",
    },
    hi: {
      text: "पश्चिमी द्वार में ऊंचा खुला मेहराब, नीले लकड़ी जैसे मुखभाग और हल्के रंग के स्तंभ साथ दिखाई देते हैं। छत के क्रॉस आकार के फिनियल पर ध्यान दें, जो कांगला की स्थापत्य शैली की खास पहचान है।",
      audio: "/audio/kangla/hi/western-gate.mp3",
    },
    mni: {
      text: "ꯅꯣꯡꯆꯨꯞ ꯊꯣꯡꯗ ꯑꯋꯥꯡꯕ ꯑꯆꯥꯎꯕ ꯊꯣꯡꯃꯥꯏ, ꯍꯤꯒꯣꯛꯀꯤ ꯃꯥꯃꯪ ꯑꯃꯗꯤ ꯀꯨꯆꯨ ꯇꯥꯏꯐꯛꯄ ꯃꯆꯨꯒꯤ ꯌꯨꯝꯕꯤ ꯂꯩ꯫ ꯌꯨꯝꯊꯛꯇ ꯂꯥꯟꯅꯕ ꯆꯤꯔꯣꯡ, ꯀꯥꯡꯂꯒꯤ ꯇꯣꯞꯇꯣꯞꯄ ꯀꯥꯡꯂꯒꯤ ꯌꯨꯝꯁꯥ ꯁꯥꯕꯒꯤ ꯃꯇꯤꯛ ꯑꯃꯅꯤ।",
      audio: "/audio/kangla/mni/western-gate.mp3",
    },
  },
  pakhangba: {
    en: {
      text: "Pakhangba Laishang is a place of worship within Kangla. The white shrine, layered roof and raised approach sit within an open green setting. Explore its exterior with respect for its living religious significance.",
      audio: "/audio/kangla/en/pakhangba.mp3",
    },
    hi: {
      text: "पाखंगबा लैशांग कांगला के भीतर स्थित एक पूजा स्थल है। सफेद मंदिर, परतदार छत और ऊंचा प्रवेश मार्ग खुले हरे परिसर में स्थित हैं। इसके जीवंत धार्मिक महत्व का सम्मान करते हुए बाहरी हिस्से को देखें।",
      audio: "/audio/kangla/hi/pakhangba.mp3",
    },
    mni: {
      text: "ꯄꯥꯈꯪꯕ ꯂꯥꯢꯁꯪ ꯑꯁꯤ ꯀꯪꯂꯥꯒꯤ ꯃꯅꯨꯡꯗ ꯂꯩꯕ ꯂꯥꯢꯁꯪ ꯑꯃꯅꯤ। ꯑꯉꯧꯕ ꯂꯥꯢꯁꯪ, ꯊꯧꯒꯠꯂꯕ ꯊꯥꯀ, ꯑꯃꯁꯨꯡ ꯑꯋꯥꯡꯕ ꯂꯝꯕꯤ ꯑꯁꯤ ꯑꯁꯪꯕ ꯂꯩꯄꯥꯛꯇ ꯂꯩ। ꯃꯁꯤꯒꯤ ꯃꯄꯥꯟ ꯑꯣꯏꯕ ꯃꯐꯝꯁꯤꯗꯨ ꯂꯩꯔꯤꯕ ꯂꯥꯏꯁꯤꯡꯒꯤ ꯃꯥꯡꯗꯥ ꯌꯥꯝ ꯅꯨꯡꯁꯤꯅ ꯌꯦꯡꯉꯨ।",
      audio: "/audio/kangla/mni/pakhangba.mp3",
    },
  },
};

/**
 * The Google 3D explorer names the same landmarks differently, and covers five
 * more that have no recording yet. Anything absent here simply shows no
 * narration control, which is the honest outcome.
 */
const PLACE_ALIASES: Record<string, string> = {
  "kangla-sha": "guardians",
  "pakhangba-laishang": "pakhangba",
  "western-gate": "western-gate",
};

/** The tracks for a landmark id from either surface, or `undefined`. */
export function narrationFor(id: string | null | undefined): NarrationSet | undefined {
  if (!id) return undefined;
  return kanglaNarration[PLACE_ALIASES[id] ?? id];
}
