/**
 * Mock operations data for the host + admin slice.
 *
 * This is deliberately separate from `@/lib/data` (the public catalogue): it
 * models the back-office — applications in review, a host's own listings, and
 * the booking ledger. Swap these arrays for Supabase queries in Phase 7; the
 * shapes are already the ones the UI consumes.
 */

import type {
  HostApplicationRecord,
  HostBookingRecord,
  HostListingRecord,
  MonthPoint,
} from "./types";

export const hostApplications: HostApplicationRecord[] = [
  {
    id: "app-1001",
    reference: "YEN-HST-2026-1001",
    userId: "usr-2201",
    hostType: "homestay",
    propertyName: "Leikai Yumjao Homestay",
    propertyAddress: "Thangmeiband Polem Leikai, near Kangla West Gate",
    district: "Imphal West",
    description:
      "A hundred-year-old Meitei yumjao with four guest rooms around the courtyard, a mangol veranda and morning tea served from the family kitchen.",
    status: "pending",
    createdAt: "2026-09-14T09:12:00+05:30",
    applicantName: "Thoibi Ningthoujam",
    email: "thoibi.n@example.in",
    phone: "+91 98561 20114",
    capacity: 8,
    photoCount: 6,
  },
  {
    id: "app-1002",
    reference: "YEN-HST-2026-1002",
    userId: "usr-2202",
    hostType: "eatery",
    propertyName: "Ima Chaobi's Eromba Kitchen",
    propertyAddress: "Ima Keithel north block, stall 44, Imphal",
    district: "Imphal West",
    description:
      "Twelve-seat kitchen behind the mothers' market. Eromba, singju, ooti and chak-hao kheer cooked to the day's market greens.",
    status: "pending",
    createdAt: "2026-09-13T16:40:00+05:30",
    applicantName: "Chaobi Devi Laishram",
    email: "chaobi.kitchen@example.in",
    phone: "+91 91234 88190",
    capacity: 12,
    photoCount: 4,
  },
  {
    id: "app-1003",
    reference: "YEN-HST-2026-1003",
    userId: "usr-2203",
    hostType: "guide",
    propertyName: "Shirui Ridge Walks",
    propertyAddress: "Shirui village, Ukhrul town road",
    district: "Ukhrul",
    description:
      "Tangkhul-led ridge walks to the Shirui lily meadows with a village council permit, first-aid certification and two porters.",
    status: "approved",
    adminNotes: "Permit and first-aid certificate verified on 2026-09-10.",
    createdAt: "2026-09-08T11:05:00+05:30",
    applicantName: "Ramkashing Shaiza",
    email: "ram.shaiza@example.in",
    phone: "+91 97741 33025",
    capacity: 10,
    photoCount: 8,
  },
  {
    id: "app-1004",
    reference: "YEN-HST-2026-1004",
    userId: "usr-2204",
    hostType: "experience",
    propertyName: "Wangkhei Phee Loom Session",
    propertyAddress: "Wangkhei Ayangpalli, loom shed behind the family house",
    district: "Imphal East",
    description:
      "Three-hour loin-loom session on the Wangkhei phee: warping, motif counting and a woven sample the guest takes home.",
    status: "pending",
    createdAt: "2026-09-16T08:20:00+05:30",
    applicantName: "Binodini Khumanthem",
    email: "binodini.weaves@example.in",
    phone: "+91 90890 51177",
    capacity: 6,
    photoCount: 5,
  },
  {
    id: "app-1005",
    reference: "YEN-HST-2026-1005",
    userId: "usr-2205",
    hostType: "homestay",
    propertyName: "Phumdi Edge Cottage",
    propertyAddress: "Thanga Karang road, Loktak east bank",
    district: "Bishnupur",
    description:
      "Two bamboo cottages on stilts at the lake edge, with a fisherman host, dawn paddle-outs and dinner of lake fish and ngari.",
    status: "approved",
    adminNotes: "Life jackets and boat licence on file. Featured candidate.",
    createdAt: "2026-09-02T18:30:00+05:30",
    applicantName: "Tomba Sanasam",
    email: "tomba.thanga@example.in",
    phone: "+91 88370 44120",
    capacity: 6,
    photoCount: 9,
  },
  {
    id: "app-1006",
    reference: "YEN-HST-2026-1006",
    userId: "usr-2206",
    hostType: "eatery",
    propertyName: "Zeliangrong Kitchen Tamenglong",
    propertyAddress: "Tamenglong bazaar upper road",
    district: "Tamenglong",
    description:
      "Smoked pork with axone, bamboo-shoot curry and black rice, cooked on a wood fire for groups of up to sixteen.",
    status: "rejected",
    adminNotes:
      "No kitchen hygiene certificate and no running-water photo. Invited to reapply once both are in place.",
    createdAt: "2026-08-28T13:15:00+05:30",
    applicantName: "Gaikhanpou Kamei",
    email: "gaikhanpou.k@example.in",
    phone: "+91 96150 27784",
    capacity: 16,
    photoCount: 2,
  },
  {
    id: "app-1007",
    reference: "YEN-HST-2026-1007",
    userId: "usr-2207",
    hostType: "guide",
    propertyName: "Kangla Heritage Walks",
    propertyAddress: "Kangla Fort west gate, Imphal",
    district: "Imphal West",
    description:
      "Two-hour fort walk in Meiteilon, English and Hindi covering Kangla Sha, the coronation ground and the 1891 siege.",
    status: "pending",
    createdAt: "2026-09-17T10:02:00+05:30",
    applicantName: "Rajkumar Meitei",
    email: "rk.kanglawalks@example.in",
    phone: "+91 94021 66531",
    capacity: 15,
    photoCount: 3,
  },
  {
    id: "app-1008",
    reference: "YEN-HST-2026-1008",
    userId: "usr-2208",
    hostType: "experience",
    propertyName: "Andro Pottery Firing",
    propertyAddress: "Andro village potters' lane, Imphal East",
    district: "Imphal East",
    description:
      "Coil-and-beat pottery without a wheel, then an open firing in the village kiln. Includes the Andro cultural complex walk.",
    status: "approved",
    adminNotes: "Village council consent letter attached.",
    createdAt: "2026-08-21T09:45:00+05:30",
    applicantName: "Ibeyaima Chanambam",
    email: "ibeyaima.andro@example.in",
    phone: "+91 99571 28844",
    capacity: 8,
    photoCount: 7,
  },
  {
    id: "app-1009",
    reference: "YEN-HST-2026-1009",
    userId: "usr-2209",
    hostType: "homestay",
    propertyName: "Dzuko Base Lodge",
    propertyAddress: "Senapati town, Mao road junction",
    district: "Senapati",
    description:
      "Trekker lodge with eight bunks, drying room and 4am breakfast for the Dzuko valley start.",
    status: "pending",
    createdAt: "2026-09-11T20:05:00+05:30",
    applicantName: "Asenla Mao",
    email: "asenla.lodge@example.in",
    phone: "+91 90898 11206",
    capacity: 8,
    photoCount: 5,
  },
  {
    id: "app-1010",
    reference: "YEN-HST-2026-1010",
    userId: "usr-2210",
    hostType: "experience",
    propertyName: "Moirang Polo Ground Ride",
    propertyAddress: "Moirang Khunou, Bishnupur",
    district: "Bishnupur",
    description:
      "An hour on a Manipuri pony with a sagol kangjei club, taught by a player from the Moirang team.",
    status: "rejected",
    adminNotes: "Insufficient insurance cover for riders. Reapply with a policy copy.",
    createdAt: "2026-08-19T15:25:00+05:30",
    applicantName: "Keisham Ibohal",
    email: "ibohal.polo@example.in",
    phone: "+91 88118 40399",
    capacity: 4,
    photoCount: 6,
  },
  {
    id: "app-1011",
    reference: "YEN-HST-2026-1011",
    userId: "usr-2211",
    hostType: "eatery",
    propertyName: "Hao Kitchen Churachandpur",
    propertyAddress: "Tuibong bazar, Churachandpur",
    district: "Churachandpur",
    description:
      "Kuki-Zo home kitchen: sawhchiar, smoked beef with bekang and a vegetarian thali on request.",
    status: "pending",
    createdAt: "2026-09-15T12:55:00+05:30",
    applicantName: "Niangngaihching Haokip",
    email: "niang.haokitchen@example.in",
    phone: "+91 70058 62211",
    capacity: 20,
    photoCount: 4,
  },
  {
    id: "app-1012",
    reference: "YEN-HST-2026-1012",
    userId: "usr-2212",
    hostType: "guide",
    propertyName: "Keibul Lamjao Sangai Watch",
    propertyAddress: "Keibul Lamjao park gate, Thoubal side",
    district: "Thoubal",
    description:
      "Dawn watch for the brow-antlered sangai from the park watchtower, with binoculars and a forest department escort.",
    status: "approved",
    adminNotes: "Forest department escort arrangement confirmed in writing.",
    createdAt: "2026-08-30T06:40:00+05:30",
    applicantName: "Sanahal Thokchom",
    email: "sanahal.sangai@example.in",
    phone: "+91 95080 77413",
    capacity: 6,
    photoCount: 10,
  },
];

/** Listings owned by the signed-in host (see `/host/dashboard`). */
export const hostListings: HostListingRecord[] = [
  {
    id: "lst-01",
    title: "Leikai Yumjao — courtyard room",
    kind: "homestay",
    district: "Imphal West",
    location: "Thangmeiband, Imphal",
    pricePerNight: 2400,
    status: "live",
    occupancyPct: 72,
    rating: 4.8,
    reviewCount: 46,
    image: "/file-uploads/h111.avif",
    imageAlt: "Courtyard of a traditional Meitei house with a tin-roofed veranda",
  },
  {
    id: "lst-02",
    title: "Leikai Yumjao — mangol loft",
    kind: "homestay",
    district: "Imphal West",
    location: "Thangmeiband, Imphal",
    pricePerNight: 1800,
    status: "live",
    occupancyPct: 64,
    rating: 4.6,
    reviewCount: 31,
    image: "/file-uploads/h112.avif",
    imageAlt: "Timber loft bedroom with woven mats and a low window",
  },
  {
    id: "lst-03",
    title: "Eromba and singju supper",
    kind: "experience",
    district: "Imphal West",
    location: "Family kitchen, Thangmeiband",
    pricePerNight: 750,
    status: "live",
    occupancyPct: 81,
    rating: 4.9,
    reviewCount: 58,
    image: "/file-uploads/manipuri-food-leaf.webp",
    imageAlt: "Manipuri meal of rice, eromba and greens served on a brass plate",
  },
  {
    id: "lst-04",
    title: "Morning loom hour",
    kind: "experience",
    district: "Imphal West",
    location: "Loom shed, Thangmeiband",
    pricePerNight: 600,
    status: "paused",
    occupancyPct: 0,
    rating: 4.7,
    reviewCount: 12,
    image: "/file-uploads/phanek.jpeg",
    imageAlt: "Hands working a striped phanek on a loin loom",
  },
];

/** Upcoming bookings against the signed-in host's listings. */
export const hostBookings: HostBookingRecord[] = [
  {
    id: "bkg-h-01",
    kind: "homestay",
    refId: "lst-01",
    refTitle: "Leikai Yumjao — courtyard room",
    userId: "usr-3301",
    startDate: "2026-09-24",
    endDate: "2026-09-27",
    guests: 2,
    totalPrice: 7200,
    status: "confirmed",
    createdAt: "2026-09-08T10:00:00+05:30",
    guestName: "Aditi Barua",
    guestOrigin: "Guwahati",
    nights: 3,
  },
  {
    id: "bkg-h-02",
    kind: "experience",
    refId: "lst-03",
    refTitle: "Eromba and singju supper",
    userId: "usr-3302",
    startDate: "2026-09-25",
    guests: 4,
    totalPrice: 3000,
    status: "confirmed",
    createdAt: "2026-09-12T19:20:00+05:30",
    guestName: "Marcus Lieven",
    guestOrigin: "Berlin",
    nights: 1,
  },
  {
    id: "bkg-h-03",
    kind: "homestay",
    refId: "lst-02",
    refTitle: "Leikai Yumjao — mangol loft",
    userId: "usr-3303",
    startDate: "2026-10-02",
    endDate: "2026-10-05",
    guests: 2,
    totalPrice: 5400,
    status: "pending",
    createdAt: "2026-09-17T08:05:00+05:30",
    guestName: "Rhea Pillai",
    guestOrigin: "Bengaluru",
    nights: 3,
  },
  {
    id: "bkg-h-04",
    kind: "homestay",
    refId: "lst-01",
    refTitle: "Leikai Yumjao — courtyard room",
    userId: "usr-3304",
    startDate: "2026-10-09",
    endDate: "2026-10-12",
    guests: 3,
    totalPrice: 7200,
    status: "confirmed",
    createdAt: "2026-09-18T14:45:00+05:30",
    guestName: "Tenzin Norbu",
    guestOrigin: "Darjeeling",
    nights: 3,
  },
];

/** The platform-wide booking ledger shown in `/admin/bookings`. */
export const adminBookings: HostBookingRecord[] = [
  ...hostBookings,
  {
    id: "bkg-a-05",
    kind: "tour",
    refId: "tour-loktak-3d",
    refTitle: "Loktak and the valley — 3 days",
    userId: "usr-3310",
    startDate: "2026-10-14",
    endDate: "2026-10-17",
    guests: 6,
    totalPrice: 64800,
    status: "confirmed",
    createdAt: "2026-09-06T11:30:00+05:30",
    guestName: "Priya Venkatesh",
    guestOrigin: "Chennai",
    nights: 3,
  },
  {
    id: "bkg-a-06",
    kind: "experience",
    refId: "exp-andro-pottery",
    refTitle: "Andro pottery firing",
    userId: "usr-3311",
    startDate: "2026-09-21",
    guests: 2,
    totalPrice: 1800,
    status: "completed",
    createdAt: "2026-08-30T09:15:00+05:30",
    guestName: "Sanjoy Debbarma",
    guestOrigin: "Agartala",
    nights: 1,
  },
  {
    id: "bkg-a-07",
    kind: "transport",
    refId: "trn-sumo-ukhrul",
    refTitle: "Shared sumo — Imphal to Ukhrul",
    userId: "usr-3312",
    startDate: "2026-09-29",
    guests: 2,
    totalPrice: 1200,
    status: "pending",
    createdAt: "2026-09-19T07:40:00+05:30",
    guestName: "Lily Shimray",
    guestOrigin: "Ukhrul",
    nights: 1,
  },
  {
    id: "bkg-a-08",
    kind: "table",
    refId: "eat-ima-eromba",
    refTitle: "Ima Chaobi's Eromba Kitchen",
    userId: "usr-3313",
    startDate: "2026-09-22",
    guests: 5,
    totalPrice: 2250,
    status: "cancelled",
    createdAt: "2026-09-09T17:10:00+05:30",
    guestName: "Hiroshi Tanaka",
    guestOrigin: "Osaka",
    nights: 1,
  },
  {
    id: "bkg-a-09",
    kind: "homestay",
    refId: "lst-thanga-01",
    refTitle: "Phumdi Edge Cottage",
    userId: "usr-3314",
    startDate: "2026-11-01",
    endDate: "2026-11-04",
    guests: 4,
    totalPrice: 10500,
    status: "confirmed",
    createdAt: "2026-09-15T21:05:00+05:30",
    guestName: "Anna Kowalski",
    guestOrigin: "Kraków",
    nights: 3,
  },
  {
    id: "bkg-a-10",
    kind: "experience",
    refId: "exp-shirui-walk",
    refTitle: "Shirui ridge walk",
    userId: "usr-3315",
    startDate: "2026-10-20",
    guests: 3,
    totalPrice: 4500,
    status: "confirmed",
    createdAt: "2026-09-16T13:25:00+05:30",
    guestName: "Devika Nair",
    guestOrigin: "Kochi",
    nights: 1,
  },
  {
    id: "bkg-a-11",
    kind: "tour",
    refId: "tour-hills-5d",
    refTitle: "Hill districts loop — 5 days",
    userId: "usr-3316",
    startDate: "2026-12-02",
    endDate: "2026-12-07",
    guests: 8,
    totalPrice: 148000,
    status: "pending",
    createdAt: "2026-09-19T18:50:00+05:30",
    guestName: "Aaron Fernandes",
    guestOrigin: "Mumbai",
    nights: 5,
  },
  {
    id: "bkg-a-12",
    kind: "table",
    refId: "eat-hao-kitchen",
    refTitle: "Hao Kitchen Churachandpur",
    userId: "usr-3317",
    startDate: "2026-09-20",
    guests: 6,
    totalPrice: 3600,
    status: "completed",
    createdAt: "2026-09-02T12:00:00+05:30",
    guestName: "Lalnunmawi Hmar",
    guestOrigin: "Aizawl",
    nights: 1,
  },
];

/** Platform bookings confirmed per month, current travel year. */
export const bookingsByMonth: MonthPoint[] = [
  { label: "Jan", value: 62 },
  { label: "Feb", value: 74 },
  { label: "Mar", value: 91 },
  { label: "Apr", value: 78 },
  { label: "May", value: 64 },
  { label: "Jun", value: 41 },
  { label: "Jul", value: 38 },
  { label: "Aug", value: 57 },
  { label: "Sep", value: 96 },
  { label: "Oct", value: 118 },
  { label: "Nov", value: 154 },
  { label: "Dec", value: 132 },
];

/** Host applications received per month. */
export const applicationsByMonth: MonthPoint[] = [
  { label: "Apr", value: 6 },
  { label: "May", value: 9 },
  { label: "Jun", value: 7 },
  { label: "Jul", value: 11 },
  { label: "Aug", value: 14 },
  { label: "Sep", value: 21 },
];

/** Payouts released to the signed-in host, last six months (INR). */
export const hostEarningsByMonth: MonthPoint[] = [
  { label: "Apr", value: 21600 },
  { label: "May", value: 18400 },
  { label: "Jun", value: 9600 },
  { label: "Jul", value: 12200 },
  { label: "Aug", value: 24800 },
  { label: "Sep", value: 31400 },
];

/** The signed-in host's own application, surfaced on their dashboard. */
export const myApplication: HostApplicationRecord = hostApplications[0];
