import type { Metadata } from "next";
import Link from "next/link";

import { LegalBody, type LegalSection } from "@/components/content/legal-page";
import { NoteBox } from "@/components/content/prose";
import { PageHero } from "@/components/content/page-hero";

export const metadata: Metadata = {
  title: "Privacy notice",
  description:
    "What Manipur Tourism collects, why, how long we keep it, who we share it with, and the rights you have over it. Written for a demonstration site, honestly.",
};

const LAST_UPDATED = "20 September 2026";

const sections: LegalSection[] = [
  {
    id: "summary",
    title: "The short version",
    body: (
      <>
        <p>
          Manipur Tourism is a demonstration site. It is
          not a commercial travel business, it does not take payments, and it collects as little
          about you as it can get away with.
        </p>
        <ul>
          <li>We ask for your name, email and message only when you choose to contact us.</li>
          <li>We do not sell personal data, and we do not run advertising trackers.</li>
          <li>We do not knowingly collect anything from children under 13.</li>
          <li>
            You can ask us what we hold, ask for it to be corrected, or ask for it to be deleted.
          </li>
        </ul>
        <p>
          The rest of this notice is the detail. If anything here is unclear, ask us through the{" "}
          <Link href="/contact">contact form</Link>.
        </p>
      </>
    ),
  },
  {
    id: "who-we-are",
    title: "Who we are",
    body: (
      <>
        <p>
          Manipur Tourism is a student and volunteer project developed for an initiative focused on tourism in
          Manipur, India, released around World Tourism Day. The team operates remotely and does not
          maintain a public office.
        </p>
        <p>
          For any question about this notice or about data we may hold, write to us at{" "}
          <strong>privacy@example.com</strong> — a placeholder address for the prototype — or use
          the <Link href="/contact">contact form</Link>, which reaches the same place.
        </p>
      </>
    ),
  },
  {
    id: "what-we-collect",
    title: "What we collect",
    body: (
      <>
        <h3>Information you give us</h3>
        <ul>
          <li>
            <strong>Contact form:</strong> your name, email address, enquiry type, subject and
            message.
          </li>
          <li>
            <strong>Account details</strong>, if account features are enabled in the demo: your
            name, email address and an authentication identifier. We never store a plaintext
            password.
          </li>
          <li>
            <strong>Prototype bookings and itineraries:</strong> the dates, guest counts and
            listings you select while trying the booking or AI planning flows.
          </li>
          <li>
            <strong>Host applications:</strong> the property or service details you submit if you
            walk through the hosting flow.
          </li>
        </ul>

        <h3>Information collected automatically</h3>
        <ul>
          <li>
            Standard server and hosting logs, which typically include an IP address, a timestamp,
            the page requested and a user-agent string. These are generated by our hosting provider
            rather than by us.
          </li>
          <li>
            Aggregate, privacy-respecting usage counts, if analytics are enabled on the deployment —
            for example how many people opened the responsible travel page. We do not build
            advertising profiles.
          </li>
        </ul>

        <h3>What we do not collect</h3>
        <p>
          We do not take payment card details, we do not ask for identity documents, permits or
          passport numbers, and we do not track your location.
        </p>
      </>
    ),
  },
  {
    id: "why",
    title: "Why we use it",
    body: (
      <>
        <ul>
          <li>
            <strong>To reply to you.</strong> If you send a message, we use your email to answer it.
          </li>
          <li>
            <strong>To operate the prototype.</strong> Saved itineraries, demo bookings and host
            applications only work if they are stored against something.
          </li>
          <li>
            <strong>To keep the site working and safe.</strong> Logs help us find errors and abuse.
          </li>
          <li>
            <strong>To improve the product.</strong> Aggregate usage tells us which pages are worth
            writing more of.
          </li>
        </ul>
        <p>
          Where a legal basis is required, we rely on your consent for optional features, on
          legitimate interests for security and for improving the service, and on the steps
          necessary to respond to your request where you have contacted us.
        </p>
      </>
    ),
  },
  {
    id: "ai",
    title: "AI features",
    body: (
      <>
        <p>
          The AI concierge drafts itineraries from the prompt you give it together with our own
          catalogue of places, stays and experiences. Your prompt is sent to a third-party model
          provider to generate the response.
        </p>
        <ul>
          <li>Do not put anything sensitive into the planner — treat it as a public message.</li>
          <li>
            Generated itineraries are suggestions. They can be wrong about timings, prices, opening
            hours and access, and they must never be used as a substitute for checking permits,
            advisories or road conditions with official sources.
          </li>
          <li>
            We do not use your prompts to train models ourselves. The provider processes them under
            its own terms.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: "cookies",
    title: "Cookies and local storage",
    body: (
      <>
        <p>
          We use the smallest set of cookies and browser storage that makes the site work: a
          preference for light or dark theme, and — where account features are enabled — a session
          cookie that keeps you signed in.
        </p>
        <p>
          We do not run advertising or cross-site tracking cookies. You can clear this storage in
          your browser settings at any time; the only consequence is that preferences reset and you
          will be signed out.
        </p>
      </>
    ),
  },
  {
    id: "sharing",
    title: "Who else sees it",
    body: (
      <>
        <p>We share personal data only with the service providers that make the site run:</p>
        <ul>
          <li>our hosting and content-delivery provider, which serves the pages and keeps logs;</li>
          <li>our database provider, where prototype records are stored;</li>
          <li>the AI model provider, for prompts you submit to the planner;</li>
          <li>an email provider, if and when one is connected to the contact form.</li>
        </ul>
        <p>
          We do not sell personal data, we do not trade it, and we do not pass it to homestays,
          guides or tour operators unless you have explicitly asked us to make an introduction. We
          may disclose information where we are legally required to.
        </p>
        <p>
          Some of these providers operate outside India. Where data is transferred internationally,
          we rely on the provider&apos;s standard contractual protections.
        </p>
      </>
    ),
  },
  {
    id: "retention",
    title: "How long we keep it",
    body: (
      <>
        <ul>
          <li>
            <strong>Contact messages:</strong> for as long as it takes to resolve the conversation,
            and up to twelve months afterwards.
          </li>
          <li>
            <strong>Prototype accounts, itineraries and demo bookings:</strong> until you ask us to
            delete them, or until the demonstration deployment is taken down — whichever comes first.
          </li>
          <li>
            <strong>Server logs:</strong> for the short retention period set by our hosting
            provider, typically a matter of weeks.
          </li>
        </ul>
        <p>
          When the project&apos;s demo deployment ends, the associated database is intended to be
          deleted rather than archived.
        </p>
      </>
    ),
  },
  {
    id: "your-rights",
    title: "Your rights",
    body: (
      <>
        <p>
          Depending on where you live, you may have the right to access a copy of your data, to have
          it corrected, to have it erased, to restrict or object to how we use it, to withdraw
          consent, and to complain to a data protection authority. Indian users have comparable
          rights under the Digital Personal Data Protection framework.
        </p>
        <p>
          To exercise any of them, email <strong>privacy@example.com</strong> or use the{" "}
          <Link href="/contact">contact form</Link> and choose &ldquo;Something else&rdquo;. We aim
          to respond within 30 days. We will ask you to confirm your identity before acting on a
          request, so that nobody can use this route to access someone else&apos;s data.
        </p>
      </>
    ),
  },
  {
    id: "security",
    title: "Security",
    body: (
      <>
        <p>
          The site is served over HTTPS, secrets are held in environment variables rather than in the
          codebase, and access to the database is restricted to the team. Passwords, where accounts
          exist, are handled by our authentication provider and are never stored by us in readable
          form.
        </p>
        <p>
          That said: this is a prototype built as a demonstration, not a hardened production
          system. Please do not enter anything into it that you would be unhappy to see disclosed.
        </p>
      </>
    ),
  },
  {
    id: "children",
    title: "Children",
    body: (
      <p>
        The site is not directed at children under 13 and we do not knowingly collect their personal
        data. If you believe a child has sent us information, contact us and we will delete it.
      </p>
    ),
  },
  {
    id: "changes",
    title: "Changes to this notice",
    body: (
      <p>
        If this notice changes materially, we will update the date at the top of the page and, where
        the change is significant, note it on the site. Continuing to use Manipur Tourism after a change
        means you accept the updated notice.
      </p>
    ),
  },
];

export default function PrivacyPage() {
  return (
    <>
      <PageHero
        eyebrow={`Privacy · Last updated ${LAST_UPDATED}`}
        title="What we collect, and — mostly — what we don't."
        lede="A short notice for a small project. We would rather describe exactly what a demonstration site does than borrow a policy written for a company we are not."
      >
        <NoteBox title="Plain summary" className="my-0 max-w-[60ch]">
          <p>
            Contact details only if you send us something. No advertising trackers. No sale of data.
            Ask us and we will delete what we hold.
          </p>
        </NoteBox>
      </PageHero>

      <LegalBody sections={sections} />
    </>
  );
}
